# pgsql.yml

---

- name: pgsql | create role
  sudo: yes
  sudo_user: postgres
  postgresql_user:  name={{ database_user }} password={{ database_userpw }} role_attr_flags=NOSUPERUSER


- name: pgsql | create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: >
    name={{ database_dbname }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'


- name: pgsql | create Privs
  sudo: yes
  sudo_user: postgres
  postgresql_privs:  >
    database={{ database_dbname }}
    roles={{ database_user }}
    privs=ALL
    type=database
