#postfix.yml

---

- name: postfix | load the os specific variables
  sudo: yes
  include_vars: "{{ansible_os_family | lower}}.yml"


- name: postfix | make sure the postfix packages are installed
  sudo: yes
  apt:
    pkg: "{{item}}"
    update_cache: yes
  with_items: postfix_packages

- name: postfix | mail configuration
  sudo: yes
  template:
    src: postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: reload postfix config

- name: postfix | master configuration
  sudo: yes
  template:
    src: postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: reload postfix config
